name: Tests
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          github-server-url: 'http://gitea:3000'
      - run: docker compose -f test.yml up --exit-code-from tests
      - uses: codecov/codecov-action@v4
